[versions]
commons-lang3 = "3.20.0"
lombok = "1.18.42"
mockito = "5.2.0"
junit = "6.0.2"
junit-launcher = "6.0.2"
awaitility = "4.3.0"
sonarqube = "7.2.2.6593"

[libraries]
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = {group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-launcher"}
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }

[plugins]
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }